project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!/unit-1/other-plots.qmd"
    - "!/portfolio/reflection-template.qmd"
    - "!/unit-2/web-scraping.qmd"
  resources: 
    - portfolio/reflection-template.qmd

website:
  page-navigation: true
  favicon: images/cat-monsters-horst.png
  title: "Advanced R"
  description: "Homepage for STAT 541 at Cal Poly"
  site-url: "https://github.com/atheobold/stat-541-website"
  repo-url: https://github.com/atheobold/stat-541-website
  repo-actions: [issue, edit]

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#5D737E"
    right:
    - text: "License"
      href: LICENSE.md

  navbar:
    background: "#5D737E"
    logo: "images/cat-monsters-horst.png"
    alt: "A orange long haired cat curled up in a ball which three round green monsters give it pets."
    align: center
    title: false
    collapse-below: lg

    right:
      - icon: github
        href: https://github.com/atheobold/stat-541-website
        aria-label: GitHub
        
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Schedule"
        href: course-materials/calendar.qmd
      - text: "Syllabus"
        href: course-materials/syllabus.qmd
      - text: "Infrastructure"
        href: infrastructure.qmd
      - text: "Unit 1 - Communication"
        href: unit-1.qmd
      - text: "Unit 2 - Iteration"
        href: unit-2.qmd
      - text: "Portfolio"
        href: portfolio.qmd
        
  sidebar:
    - id: infrastructure
      title: "Infrastructure"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - href: infrastructure.qmd
        - href: set-up/setup-discord.qmd
        - href: set-up/setup-workflow.qmd
        - href: set-up/setup-version-control.qmd
        - href: labs/lab-1.qmd

    - id: unit-1
      title: "Unit 1"
      contents:
        - href: unit-1.qmd
        - href: unit-1/ggplot-review.qmd
        - href: unit-1/ggplot-extensions.qmd
        - href: unit-1/ggplot-leaflet.qmd
        - href: labs/lab-2.qmd
        - href: unit-1/quarto-dashboard-static.qmd
        - href: labs/lab-3.qmd
        - href: unit-1/quarto-dashboard-dynamic.qmd
        - href: labs/lab-4.qmd
        
    - id: portfolio
      title: "Portfolio"
      contents:
        - href: portfolio.qmd
        - href: portfolio/portfolio-instructions.qmd
        - href: portfolio/portfolio-rubric.qmd
        - href: portfolio/reflection-template.qmd

    - id: unit-2
      title: "Unit 2"
      contents:
        - href: unit-2.qmd
        - href: unit-2/writing-functions.qmd
        - href: unit-2/efficient-code.qmd
        - href: unit-2/iterating-functions.qmd
        - href: labs/lab-6.qmd
        - href: labs/lab-6-alt.qmd
        - href: unit-2/json.qmd
        # - href: unit-2/web-scraping.qmd
        # - href: unit-2/generative-art.qmd
    
format:
  html:
    theme:
      light: [cosmo, style/stat331.scss]
      dark: [cosmo, style/stat331.scss, style/dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    linkcolor: "#5D737E"

editor: visual