---
title: "Project 1 Final Deliverable"
editor: source
---

For this project, you and your group will collaborate to produce a stylized,
publication-ready report. The report will include an exploratory data analysis
complete with styled visualizations and polished tables which address
**at least two** research questions posed by your group.

## Weekly Checkpoints

You will complete weekly checkpoints each of which will help you craft the 
content for your final deliverable. 

- In **Week 1** you will craft the potential research questions that will guide
your analysis. 
- In **Week 2** you will write data summary functions and iterate over those
functions to create professionally styled summary tables. 
- In **Week 3** you will acquire external data using APIs and webscraping. 
- In **Week 4** you will create professionally styled visualizations using
non-standard geometries.

# Final Deliverable

Once you've completed all the checkpoints, the final step is to assemble your 
project into a report that walks the reader through **two** of your research
questions. 

The final report you create **must** have the following sections. 

## Data Context (20 points)

In this section you walk the reader through **all** the data you will use for
your analysis. As you have *multiple* datasets you will draw on, you should have
*multiple* paragraphs describing each dataset. At a minimum you should address
the following for each dataset:

- Who -- Who collected the data? If you do not know who collected the data, then
be transparent about the information you know (e.g., who published the data).

- Where -- Where were the data collected i.e., what is the observational unit?

- When -- When were the data collected?

- How -- How were the data collected?

- Why -- Why were the data collected? i.e., why are these data of interest?

## Research Questions (10 points)

In this section, you will outline the **two** research questions that will guide
your report. One question must be targeted toward the *original data* and one
question must be targeted toward a *new dataset*. 

Your research questions should be as clear and specific as possible, so it is
easy for the reader to see how your findings address these questions. 

## Data Summaries & Visualizations (50 points)

This section contains summary tables and visualizations that address your 
research question. **For each research question**, you are expected to have:

- Two summary tables

    * At least one summary table needs to be produced with a custom function
    (from Week 2).
    * At least one summary table needs to include iteration (from Week 2).

- Two data visualizations
    * At least one visualization must use a more complex geometry (from Week 4).
    
All summary tables must be professionally formatted. 

* Every table **must** have formatted values (e.g., decimals, percentages,
    currencies), boldface headers, and captions.
* **At least one** table (out of four) must incorporate additional styling
    (e.g., color, row group labels, spanner labels)

All visualizations must be professionally formatted. 

* Every visualization **must** have non-default colors, a non-default theme,
    clear labels, and an informative plot title.
* Every visualization must also have alternative (alt) text descriptions of
    which can be read by a screen reader.
    
## Data Model (10 points)

In this section you must fit **one** statistical model addressing *one* of the
research questions posed. The output of your model is expected to be 
professionally formatted so the results are easily communicated to the reader.

Either before or after your summary table, you are expected to communicate 
the findings of your statistical model and connect them back to the research
question which they address.

::: {.callout-important}
# One summary table

If you chose to fit **multiple** statistical models (e.g., comparing different
models), you are expected to collapse these multiple models into a *single* 
summary table. 
:::

## Quarto Document (10 points)

::: columns
::: {.column width="55%"}
-   uses a non-default theme
-   uses headers and subheaders to delineate the sections
-   uses table and figure numbers to reference findings
:::

::: {.column width="2%"}
:::

::: {.column width="43%"}
::: callout-warning
# Coordinated Colors

The colors from the document theme you chose should match the colors in your
plots and tables!
:::
:::
:::

<!-- # Peer Review -->

<!-- In Week 4 your group will give (and receive) feedback to another group as it -->
<!-- relates to the layout of the report and the visualizations / tables included -->
<!-- in the report.  -->

# Submission

Your final submission varies based on the course in which you are enrolled. 
Please see below for the expectations for your course. 

## STAT 431

For your final submission, your group will submit **one** GitHub repository
link and **one** HTML document. This means, you will need to choose which group
member's repository will be submitted as the final version. 

## STAT 541

For your final submission, your group will submit **one** GitHub repository
link and **one** link to the published HTML document. This means, you will need
to choose which group member's repository will be submitted as the final
version. 

To publish your document, you will need to sign up for a free [Connect Cloud](https://connect.posit.cloud/) account. I would recommend signing up with
your GitHub account, since the documents you will be publishing for Project 1 
and Project 2 live in a GitHub repository!

Once you've signed up, you need to follow these steps to publish your document:

1. Click on the "Publish" button on the left sidebar
2. Select the "From GitHub" tab
3. Select "Quarto" as the framework
4. Input the URL of your GitHub repository
5. The branch you want to push from should be "main"
6. Input the name of the HTML document you want to publish 
(e.g., `project-1.html`)
7. Select "Publish" to publish your document!

::: callout-tip
# Publish on Push

I would recommend toggling on the "Automatically publish on push" option, so 
your document will automatically update when you push changes to your GitHub
repository. 
:::
