---
title: "Project Checkpoint 6"
---

For this second check-in, you will build on the dashboard shell you created last week by adding interactivity and incorporating a new country-specific dataset. All additions should be integrated into your existing Quarto dashboard---this is not a new project, but a continuation and expansion of your current work.

## Data on a Specific Country

This week, you will choose **one** country from your original dataset to acquire additional information on. The country you choose is required to meet **at least one** of the following criteria:

- **An outlier**: A country that is unusually high or low or behaves differently than others in your dataset.
- **A representative case**: A country that reflects the global or regional trend particularly well.
- **A case of change**: A country that shows substantial change over time.

Before finalizing your country choice, verify that you can obtain additional country-specific data suitable for a dynamic visualization!

## For this checkpoint, your group should:

**On the main page:**

Now that you have your report turned into a dashboard, it is time to *cut down*
the content!

- The content included in the main page should focus on **one** research
question. Meaning, you need to choose one of your two questions to focus on!

**On a (new) second page:**

- Acquire and incorporate new country-specific data relevant to your project.

- Include a short "Why this country?" section (2–3 sentences) on your dashboard.

**Integrate Dynamic Visualizations**

- Create one dynamic visualization (e.g., an animated plot or a
`plotly` interactive graphic)
- Create one `leaflet` map 

One plot should be made for the original data (on the main page) and one plot
should be made for the new country-specific data. You get to choose which plot
is best suited for each context!

**Think about formatting / structure:**

The content in your dashboard should be organized in a way that is easy for the reader to view.

For tabsets:

- It should be *obvious* that the reader can click on them!
- More than three tabsets gets overwhelming!
- Sufficient space should be given to the tabsets, so their titles appear horizontally.

For plots:

- Sufficient space should be given to the plot!
- The text on the plot should be legible without needing to zoom in or squint.
- The colors on the plot should coordinate with the colors of the dashboard theme.

For text descriptions:

- Keep these short and easy to read!
- Highlight key words or findings to bring them out.
