---
title: "Final Portfolio Instructions"
subtitle: "Creating a Personal Website with Quarto & GitHub Pages"
format: html
editor: source
---

GitHub is an incredibly useful tool for project management and collaboration. It
also has several useful features for professional promotion: you can host your
own site on github using [GitHub pages](https://pages.github.com/), describe
yourself using a GitHub developer profile, and even use
[resume.github.io](http://resume.github.io/) to generate a resume summary of
your activity on GitHub (you must opt-in by [starring the project page](https://github.com/resume/resume.github.com)). 

The development of Quarto has made it incredibly simple to 
[generate websites](https://quarto.org/docs/websites/), which can be easily 
hosted by GitHub Pages. 

## Instructions for Creating a Personal Website

If you've never made a personal website, you will need to create one! There are
**so** many resources for creating Quarto websites, but my absolute favorite 
one's are from Sam Shanny-Csik.

Follow this step-by-step guide for creating a new Quarto website: 
<https://ucsb-meds.github.io/creating-quarto-websites/

::: columns
::: {.column width="47%"}
::: {.callout-important}
# Name your project `<YourGitHubUsername>.github.io`

We're going to deploy websites using GitHub pages, and it would be nice if your
website had a professional name! I would recommend using your username, unless
you chose a username that isn't very descriptive or unique (e.g., `brandonk04`). If this is the case, I would recommend you use a more descriptive name for your project (e.g., `brandon-kim-04`). 
:::
:::

::: {.column width="5%"}
:::

::: {.column width="47%"}
::: {.callout-tip}
I would strongly recommend this folder living *inside* your broader "STAT 541"
folder, at least for now!
:::
:::
:::

## Making Changes to an Existing Website

So you already have a personal website? Great! Let's get started making blog
posts for your website!

We're going to follow another one of Sam Shanny-Csik's guides for integrating
blog posts into your existing website:

<https://samanthacsik.github.io/posts/2022-10-24-quarto-blogs/>

::: {.callout-important}
I'm expecting that your posts are contained in a `portfolio` folder, so they 
are easy for me to find. 
:::

By the end of the quarter, you should have blog posts for the following 
projects you've completed:

- Advanced Visualizations
- Quarto Dashboards (Static)
- Quarto Dashboards (Dynamic)
- Quarto with WebR
- JSON Data & APIs
- Webscraping
- Generative Art

## Additional Styling Options

In case you are interested in styling your website further, I would recommend
looking over [this presentation](https://samanthacsik.github.io/talks_workshops/2022-10-10-customizing-quarto-websites/) on using `.scss` and `.sass` files. 