---
title: "Lab 4"
subtitle: "Transforming a Static Dashboard into an Interactive Dashboard"
editor: source
---

For this lab assignment, you are tasked with transforming your previous static
dashboard into an interactive dashboard using either Shiny or webR. 

## Dashboard Requirements

::: columns
::: {.column width="47%"}
**If you created a Shiny dashboard**

Your dashboard **must** have the following:

- at least one opportunity for user input via a slide bar
- at least one opportunity for user input via check boxes 

These interactive features are expected to be used to:

- update at least one visualization
- update at least one of your "quick information" cards

:::

::: {.column width="3%"}
:::

::: {.column width="50%"}
**If you created a webR dashboard**

Your dashboard **must** have the following:

- a code chunk box that allows the user to interact with code used for your
dashboard
- instructions on how to modify the code

You can incorporate this code box to modify your visualization or to modify a 
table. 

You will need to put your educator hat on when making the instructions for how 
the user needs to interact your code box. Consider the following:

- what "skeleton" code you want to provide
- what instructions / details would help the user modify the code you provided
- what messages / warnings might you want to provide if the user inputs 
something you didn't expect
:::
:::

::: {.callout-tip}
# Interactive Table 

You are free to swap one of your visualizations out for an interactive table!
:::

## Submission

You are required to submit **both** the link to your GitHub repository 
containing your source code **and** a link to your [published]{.underline}
dashboard. You are expected to publish your dashboard through
[Quarto Pub](https://quarto.org/docs/publishing/quarto-pub.html), a free
publishing service for static content created with Quarto. 
