---
title: "STAT 541: Advanced R"
subtitle: "Spring 2025"
tbl-colwidths: [10,15,35,25,25,25]
---

This page contains an outline of the topics, content, and assignments for the quarter. Note that this schedule will be updated as the quarter progresses, with all changes documented here.

+--------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------+--------------------+------------------------------------------------------------------------------------------------------------+------------------------+
| Week                                 | Date                                            | Required Reading                                                                                    | Lecture Activities | Lab Assignment                                                                                             | Portfolio              |
+======================================+=================================================+=====================================================================================================+====================+============================================================================================================+========================+
| **1**\                               | March 31 (note no class on Monday)              | [Installing / Updating R & RStudio](/set-up/setup-workflow.qmd "Installing / Updating R & RStudio") |                    | [Lab 0 (link to GitHub repository)](https://github.com/STAT-541/lab-0 "Lab 0 (link to GitHub repository)") |                        |
| Stat 331 Review & Version Control    |                                                 |                                                                                                     |                    |                                                                                                            |                        |
|                                      |                                                 | [Version Control](/set-up/setup-version-control.qmd "Version Control")                              |                    |                                                                                                            |                        |
+--------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------+--------------------+------------------------------------------------------------------------------------------------------------+------------------------+
| **2**\                               | April 7                                         | [`ggplot` Review](/unit-1/ggplot-review.qmd "ggplot Review")                                        |                    |                                                                                                            |                        |
| Advanced Visualizations              |                                                 |                                                                                                     |                    |                                                                                                            |                        |
|                                      |                                                 | [`ggplot`Extensions](/unit-1/ggplot-extensions.qmd "ggplot Extensions")                             |                    |                                                                                                            |                        |
|                                      |                                                 |                                                                                                     |                    |                                                                                                            |                        |
|                                      |                                                 | [Making maps with `leaflet`](/unit-1/ggplot-leaflet.qmd "Making maps with leaflet")                 |                    |                                                                                                            |                        |
+--------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------+--------------------+------------------------------------------------------------------------------------------------------------+------------------------+
| **3**\                               | April 14                                        |                                                                                                     |                    | [Lab 3 Instructions](/labs/lab-3.qmd "Lab 3 Instructions")                                                 |                        |
| Quarto Dashboards (Static)           |                                                 |                                                                                                     |                    |                                                                                                            |                        |
|                                      |                                                 |                                                                                                     |                    | [Lab 3 (link to GitHub repository)](https://github.com/STAT-541/lab-3 "Lab 3 (link to GitHub repository)") |                        |
+--------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------+--------------------+------------------------------------------------------------------------------------------------------------+------------------------+
| **4**\                               | April 21                                        |                                                                                                     |                    |                                                                                                            |                        |
| Quarto Dashboards (Dynamic)          |                                                 |                                                                                                     |                    |                                                                                                            |                        |
+--------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------+--------------------+------------------------------------------------------------------------------------------------------------+------------------------+
| **5**\                               | April 28                                        |                                                                                                     |                    |                                                                                                            |                        |
| Quarto & WebR                        |                                                 |                                                                                                     |                    |                                                                                                            |                        |
+--------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------+--------------------+------------------------------------------------------------------------------------------------------------+------------------------+
| **6**\                               | May 5                                           |                                                                                                     |                    |                                                                                                            | Portfolio Instructions |
| Portfolio Week                       |                                                 |                                                                                                     |                    |                                                                                                            |                        |
+--------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------+--------------------+------------------------------------------------------------------------------------------------------------+------------------------+
| **7**\                               | May 12                                          |                                                                                                     |                    |                                                                                                            |                        |
| JSON Data & APIs                     |                                                 |                                                                                                     |                    |                                                                                                            |                        |
+--------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------+--------------------+------------------------------------------------------------------------------------------------------------+------------------------+
| **8**\                               | May 19                                          |                                                                                                     |                    |                                                                                                            |                        |
| Webscraping                          |                                                 |                                                                                                     |                    |                                                                                                            |                        |
+--------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------+--------------------+------------------------------------------------------------------------------------------------------------+------------------------+
| **9**\                               | May 26 (note Tuesday follows a Monday schedule) |                                                                                                     |                    |                                                                                                            |                        |
| Generative Art                       |                                                 |                                                                                                     |                    |                                                                                                            |                        |
+--------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------+--------------------+------------------------------------------------------------------------------------------------------------+------------------------+
| **10**\                              | June 2                                          |                                                                                                     |                    |                                                                                                            |                        |
| Portfolio Week                       |                                                 |                                                                                                     |                    |                                                                                                            |                        |
+--------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------+--------------------+------------------------------------------------------------------------------------------------------------+------------------------+
| **Finals Week** (Portfolio Meetings) | June 9                                          |                                                                                                     |                    |                                                                                                            |                        |
+--------------------------------------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------+--------------------+------------------------------------------------------------------------------------------------------------+------------------------+
